export default {
    primary : '#fff',
    lightSecondary: '#7d80df',
    secondary: '#4c51dd',
    darkSecondary: '#080811',
    tertiary: '#677483',
    grey: '#e9ebff',
    danger: '#a13f3f',
    regfont: 'quick-reg',
    medfont: 'quick-med',
    boldfont: 'quick-bold',
    lightfont: 'quick-light',
    extraboldfont: 'extra-quick-bold',
    bgLight: require('../assets/light.jpg'),
    bgDark: require('../assets/dark.jpg'),
    fontSize: 16,
    padding: 10,
    radius: 10,
    URL: 'https://tailorsmind.com/api/'
}